FROM node:20.12.2 AS build

WORKDIR /app
COPY package*.json ./
RUN npm install

COPY . .
RUN npm run build

FROM nginx:alpine as development-stage
COPY --from=build /app/dist/ /usr/share/nginx/html
COPY nginx.dev.conf /etc/nginx/nginx.conf
COPY robots.txt /usr/share/nginx/html/robots.txt
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
